/* Insert values into tables*/
INSERT INTO Kunder VALUES ('email','navn','12345678');

INSERT INTO Priser VALUES (115,'Voksen');
INSERT INTO Priser VALUES (100,'Studerende');
INSERT INTO Priser VALUES (0,'Born');

INSERT INTO Billeter VALUES (1,123456789,123456789,123456789,2015-05-07,123.45,0);

INSERT INTO VikingeSkibe VALUES ('Bjørnefjord',20, 'Båden er bygget af fyrretræ med køl og stævne af eg. Den er bygget på Oselververkstadet i Hardanger specielt til sejlads med skoleelever på Roskilde Fjord. Bådebyggerne har taget specielt hensyn til at båden skulle være god til at krydse på den sædvanligvis ret stille fjord. Derfor er det nederste bord "kølbordet" rejst, så det står mere stejlt, end det tilsvarende bord på søsterbåden Oselven. Bjørnefjord er større end oselverbådene ellers var, for at den kan rumme en hel skoleklasse. De mindre oselvere i dag fører sprydsejl men Bjørnefjord sejler med et råsejl i overensstemmelse med tidligere tiders tradition.', 'Værft: Vikingeskibsmuseet , Roskilde  (Denmark)', 'ms-appx:///Assets/Skibe/bjørnefjord.jpg');
INSERT INTO VikingeSkibe VALUES ('Blakman',9, 'Bygget af fyrretræ af Niclas i Koltri. De urolige og uforudsigelige vejrforhold, samt den heftige strøm mellem Færøerne, krævede særligt sødygtige både der samtidig var så lette at de kunne trækkes op på land. De kraftige kastevinde gjorde det nødvendigt med et lille sejlareal der tilmed var opdelt på to lave sejl.Ottemannafareren fører et luggerstorsejl og en lille sprydmesan på en stormast og en mesanmast der begge er lette at rigge af og lægge ned i båden. Årerne er hovedfremdrivningssmidlet i al slags vejr.', 'Værft: Færøerne (Danmark)', 'ms-appx:///Assets/Skibe/blakman.jpg');
INSERT INTO VikingeSkibe VALUES ('Embla',14, 'Denne store, tolvmands fyrretræsbåd er bygget i Eidi på Færøerne af Símun Johan Wolles til Vikingeskibsmuseets sejlads med skolebørn på Roskilde Fjord. Typen var sjælden i gamle dage, men enkelte både af denne størrelse blev brugt til fragt af varer og transport af personer. Embla er rigget med et trapezformet råsejl med lavt trykcenter som man brugte det til de store transportbåde op til 1870''erne.', 'Værft: Eidi, Færøerne (Denmark)', 'ms-appx:///Assets/Skibe/embla.jpg');
INSERT INTO VikingeSkibe VALUES ('Gerifuglen',12, 'Geirfuglen er bygget på Vikingeskibsmuseets værft til brug i museets sejladstjenste med 12 roere og et råsejl på omkring 20 m2', 'Værft: Vikingeskibsmuseet, Roskilde (Denmark)', 'ms-appx:///Assets/Skibe/gerifuglen.jpg');
INSERT INTO VikingeSkibe VALUES ('Helge Ask',30, 'Helge Ask er bygget på museet i 1990-91 af eg, fyr og ask. Det er en rekonstruktion af det lille krigsskib Skuldelev 5. Skibet har muligvis været et leddingskib, dvs. at det ikke blot har indgået i det lokale forsvar, men også som en af de mindste enheder i Danmarks datidige flåde. Denne flådes skibe regnedes ifølge middelalderens saga- og lovtekster fra "13-sessen" som det mindste op til "35-sessen". Sesse betyder rorbænk med to årer, og Skuldelev 5 har 26 årer og er altså en 13-sesse. Af det oprindelige skib er ca. 65% bevaret. Bunden og næsten hele bagbord side er intakt, så det har· været relativt let at rekonstruere den manglende styrbords side. Det specielle ved dette krigsskib er i øvrigt at de .øverste planker engang i skibets levetid er blevet ødelagt og derefter erstattet af planker fra et andet skib. Dette bemærkelsesværdige eksempel på genbrug allerede i vikingetiden afsløres bl.a. af at de firkantede årehuller i den "ny" øverste planke ikke har passet til åreplaceringen i Skuldelev 5 hvorfor de, som det kan ses på vraget i Vikingeskibshallen, er lukkede med træplader. Derpå har man så skåret nye, runde årehuller med det rette mellemrum. ', 'Værft: Vikingeskibsmuseet, Roskilde (Denmark)', 'ms-appx:///Assets/Skibe/helge-ask.jpg');
INSERT INTO VikingeSkibe VALUES ('Kraka Fyr',15, 'Bygget i fyr, med køl og stævne af eg. Delene i den indvendige konstruktion er fremstillet af fyr, rødel og birk. Det originale skib er bygget i Sognefjorden i Norge omkring år 1030. Det er mærkværdigvis på samme sted og på samme tid som det havgående handelsskib Skuldelev 1. Der er flere ligheder i konstruktionen af de to skibe som viser slægtskabet. F.eks. har de begge det specielle, langsgående bundknæk i skibssiden under vandlinjen. Skuldelev 6 var oprindeligt bygget som en forholdsvis lavbordet båd med 6 bordgange. Den har sandsynligvis været brugt til transport eller fragt af varer eller til fangst og fiskeri i beslægtede farvande. Den kunne ros fra ikke mindre end 14 årepositioner langs essingen. ', 'Værft: Vikingeskibsmuseet, Roskilde (Denmark)', 'ms-appx:///Assets/Skibe/kraka-fyr.jpg');
INSERT INTO VikingeSkibe VALUES ('Skjoldungen',18, 'Skjoldungen er bygget som en nyfortolkning af Skuldelev 6 og blev søsat i 2012. Den første rekonstruktion, der blev bygget ud fra Skuldelev 6, var Kraka Fyr, som blev søsat i 1998. Under bygningen af Kraka Fyr, fandt man ud af at det originale skib er bygget i Vestnorge i 1026. Erfaringerne med skibstyper fra Vestnorge, byggeriet, sejladserne og de efterfølgende rekonstruktioner af Skuldelevskibene har ført til en ny tolkning af det originale skib. Man kan især se forskellen stævnenes udformning på Kraka Fyr og Skjoldungen. Skibet er bygget i fyr, med køl og stævne af eg. Delene i den indvendige konstruktion er fremstillet af fyr, rødel og birk. Årene er fremstillet af hvidgran, så de er lette, fleksible og stærke. ', 'Værft: Vikingsskibsmuseet, Roskilde (Denmark)', 'ms-appx:///Assets/Skibe/skjoldungen.jpg');
INSERT INTO VikingeSkibe VALUES ('Krákan',9, 'Bygget af fyr med køl og stævne af eg på Vikingeskibsmuseets bådeværft i 1993. Ottemannafaren blev brugt på Færøerne til vinterfiskeri med håndliner efter torsk, lange og helleflynder. Samtidig var den før i tiden, ikke mindst på grund af dens sødygtighed, det vigtigste transportmiddel af gods og mennesker mellem øerne. Båden fører et lavt luggersejl og en sprydmesan på en stormast og en mesanmast der let kan rigges af og lægges ned i båden. Årerne er hovedfremdrivningsmidlet i al slags vejr.', 'Værft: Vikingeskibsmuseet, Roskilde (Denmark)', 'ms-appx:///Assets/Skibe/krákan.jpg');
INSERT INTO VikingeSkibe VALUES ('Oselven',13, 'Museets båd er bygget af fyrretræ med køl og stævne af eg, specielt til sejlads med skolebørn på Roskilde Fjord, men på Oselven ligger kølbordet mere vandret end på BjørneJjord. Det gør Oselven til en mere bæredygtig havbåd, mens BjørneJjord egner sig bedre til mere roligt vand. Både af denne type, men lidt mindre, brugtes omkring 1900 til fiskeri med torskegarn på åbent hav ud for Vestnorge. De var så hurtige og sødygtige at de næsten altid kunne nå i læ af land, inden dårligt vejr trak op.', 'Værft: Oselvarverkstaden, Os (Norway)', 'ms-appx:///Assets/Skibe/oselven.jpg');
INSERT INTO VikingeSkibe VALUES ('Sunnfjord',13, 'Vikingeskibsmuseets kopi blev bygget i Vestnorge i 1995 som et samarbejde mellem norske og danske bådebyggere.Den oprindelige båd blev bygget af fyrretræ i Yttrehus, Vestnorge, i 1860 til kystnært fiskeri efter torsk i Nordatlanten, og denne fyrretræsbåd er stadig i brug. Sekskeipingen har seks par årekeiper og er rigget med et råsejl.', 'Værft: Museet Kystens Arvs Bådeskott, Stadsbygd (Norway)', 'ms-appx:///Assets/Skibe/sunnfjord.jpg');
INSERT INTO VikingeSkibe VALUES ('Trolle',9, 'Denne færøbåd er bygget på museets værft til brug for skoletjeneste- og turistsejladser. Den følger nøje byggetraditionerne fra Færøerne. Skoletjenesten ønskede at få en båd af ottemannafaren Blakman''s størrelse og kvalitet, men museets færøske bådebygger Hanus Jensen ønskede ikke at bygge en tro kopi af denne båd, men valgte i stedet at bygge sin egen ottemannafar med de ønskede gode egenskaber. Sammenligner man de to både nøje, kan man tydeligt se hvor rummelig en lokal tradition kan være. De to ottemannafarer ligner ikke hinanden. De nederste bord ved kølen, "fladbordene", ligger mere vandret ud fra kølen på TrolIe end på Blakman, og Trolles køl er noget kortere end Blakmans. Det betyder at Trolles stævne bliver mere udfaldende, da bådene jo skal have samme længde overalt. Derved er Trolle blevet mere stabil og lidt hurtigere at dreje med. Det er nemlig sådan at dersom en langkølet båd er kommet til at ligge på tværs i svær brændingssø, kan det være umuligt at få forstævnen vendt op mod søen igen.', 'Værft: Vikingsskibsmuseet, Roskilde (Denmark)', 'ms-appx:///Assets/Skibe/trolle.jpg');